De-duplicate repeated HID packets
SlimeVR/SlimeVR-Server pull request #1036
Opened 2024-05-19 19:25 UTC by nekomona

Current implementation of slimenrf-receiver fills empty space with repeated duplication of the last packet to fulfill HID packet length requirement. The duplicated packets would interfere with TPS count and filtering etc.. This PR filters out duplicated packets on the server-side.

2024-05-20 21:35 UTC, sctanf approved these changes

2024-05-20 21:55 UTC, ImUrX requested changes
is it possible to not use a reference instead of copying part of an array?

2024-06-03 14:37 UTC, ImUrX approved these changes

2024-06-05 22:26 UTC, Eirenliel approved these changes

2024-06-05 22:26 UTC, Eirenliel commented
If you want to access arrays by references, you need to use ByteBuffers.

2024-06-14 15:36 UTC, merged