Hide navbar onboarding
SlimeVR/SlimeVR-Server pull request #1152
Opened 2024-09-03 16:08 UTC by JovannMC

Partially fixes #894 by allowing users to hide the onboarding button to prevent accidental clicks

![image](https://github.com/user-attachments/assets/c7a4eca2-7422-481c-8c3f-db1ad322263a)

2024-09-07 11:07 UTC, ImUrX requested changes

2024-09-07 11:07 UTC, ImUrX commented on gui/public/i18n/en/translation.ftl
> +settings-general-interface-show-navbar-onboarding-description = This changes if the "Setup Wizard" button shows on the navigation bar.
instead of "Setup Wizard" maybe you want to reference the translation key itself?
you can do that by doing `{ navbar-onboarding }`

2024-09-08 18:01 UTC, ImUrX approved these changes

2024-09-08 18:01 UTC, ImUrX commented on gui/public/i18n/en/translation.ftl
> +settings-general-interface-show-navbar-onboarding-label = Show { navbar-onboarding }
```suggestion
settings-general-interface-show-navbar-onboarding-label = Show "{ navbar-onboarding }"
```

2024-09-08 18:01 UTC, ImUrX commented on gui/public/i18n/en/translation.ftl
> +settings-general-interface-show-navbar-onboarding-label = Show { navbar-onboarding }
a little more correct

2024-09-29 02:27 UTC, ButterscotchV commented
Maybe there could also be a button in the settings to open the setup wizard so even with it hidden you could go back?

2024-09-29 12:55 UTC, JovannMC commented
> Maybe there could also be a button in the settings to open the setup wizard so even with it hidden you could go back?

I don't really see the point of having the button just in case the user wants to use it. At that point they can just temporarily show the setup wizard again because they are already in settings.

2024-10-07 20:07 UTC, ButterscotchV approved these changes

2024-10-08 17:15 UTC, merged