catch unable to find hid library
SlimeVR/SlimeVR-Server pull request #1199
Opened 2024-10-14 19:17 UTC by sctanf

2024-10-14 19:49 UTC, ImUrX requested changes
still crashes

```
java -jar Downloads/SlimeVR-Server/slimevr.jar run
21:48:30 [INFO] Using log folder: /home/uri/.local/share/dev.slimevr.SlimeVR/logs
21:48:30 [INFO] Running version e5a6322
21:48:30 [INFO] Using config dir: /home/uri/.config/dev.slimevr.SlimeVR/vrconfig.yml
21:48:30 [INFO] Starting the tracker server on port 6969...
21:48:30 [SEVERE] SLF4J: No SLF4J providers were found.
21:48:30 [SEVERE] SLF4J: Defaulting to no-operation (NOP) logger implementation
21:48:30 [SEVERE] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
21:48:30 [SEVERE] org.hid4java.HidException: Hidapi did not initialise: libudev.so.1: cannot open shared object file: No such file or directory
21:48:30 [SEVERE]       at org.hid4java.HidDeviceManager.<init>(HidDeviceManager.java:87)
21:48:30 [SEVERE]       at org.hid4java.HidServices.<init>(HidServices.java:81)
21:48:30 [SEVERE]       at org.hid4java.HidManager.getHidServices(HidManager.java:72)
21:48:30 [SEVERE]       at dev.slimevr.desktop.tracking.trackers.hid.TrackersHID.<init>(TrackersHID.kt:42)
21:48:30 [SEVERE]       at dev.slimevr.desktop.Main.main(Main.kt:130)
21:48:30 [SEVERE] Caused by: java.lang.UnsatisfiedLinkError: libudev.so.1: cannot open shared object file: No such file or directory
21:48:30 [SEVERE]       at com.sun.jna.Native.open(Native Method)
21:48:30 [SEVERE]       at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:300)
21:48:30 [SEVERE]       at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:481)
21:48:30 [SEVERE]       at com.sun.jna.Library$Handler.<init>(Library.java:197)
21:48:30 [SEVERE]       at com.sun.jna.Native.load(Native.java:618)
21:48:30 [SEVERE]       at com.sun.jna.Native.load(Native.java:592)
21:48:30 [SEVERE]       at org.hid4java.jna.HidrawHidApiLibrary.<clinit>(HidrawHidApiLibrary.java:37)
21:48:30 [SEVERE]       at org.hid4java.jna.HidApi.init(HidApi.java:123)
21:48:30 [SEVERE]       at org.hid4java.HidDeviceManager.<init>(HidDeviceManager.java:84)
21:48:30 [SEVERE]       ... 4 more
```

2024-10-14 21:35 UTC, sctanf commented
oh, it is HidException not UnsatisfiedLinkError

2024-10-15 15:52 UTC, ImUrX approved these changes

2024-10-15 23:04 UTC, ButterscotchV approved these changes

2024-10-16 01:52 UTC, merged