Clarify AutoBone error after #1185
SlimeVR/SlimeVR-Server pull request #1214
Opened 2024-10-26 05:16 UTC by ButterscotchV

The current error message doesn't really convey the issue as the error limit was just patched in. Let's make it say something more useful.

I don't think this is the best message possible since it doesn't really mention anything about an error value limit, though the end user knows nothing about this supposed error value, so maybe it would just be more confusing? I'd love thoughts and suggestions here.

2024-10-26 21:52 UTC, ImUrX approved these changes

2024-10-26 21:53 UTC, ImUrX requested changes
please change language key by appending -v2 to it and update any code trying to use the key

2024-10-28 14:43 UTC, ImUrX approved these changes

2024-10-28 15:36 UTC, Erimelowo commented on gui/public/i18n/en/translation.ftl
> +    This is likely a mounting calibration issue, make sure your tracking works first.
```suggestion
    This is likely a mounting calibration issue. Make sure your tracking works properly before trying again.
```

2024-10-28 21:48 UTC, Erimelowo approved these changes

2024-10-28 21:56 UTC, merged