2 poses calibration for yaw offset
SlimeVR/SlimeVR-Server pull request #145
Opened 2022-03-31 03:05 UTC by Louka3000

- Aligns trackers automatically from two poses. 
- Replace selecting front/back/left/right setting, and make it way more precise too.
- Support for upside-down trackers or firmware.

Took me so much time figuring out the Quaternion math. If you have a better way of doing it, give it to me, but this works!

2022-04-02 15:39 UTC, Eirenliel requested changes
Format your code and we can talk after...

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +	private static float TENTH_THIRD = 0.03333f, FIFTH_THIRD = 0.06666f;
Please don't use magic constants like this. If you need 3%, use something like 3f / 100f and 6f / 100f instead.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +	protected float mounting = 3.141592f;
Please don't redefine PI. Use `FloatMath.PI` instead.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/trackers/TrackerConfig.java
> +	public float mountingRotation = 3.141592f;
Same about PI.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/trackers/TrackerConfig.java
> +		this.mountingRotation = node.getFloat("rotation", 3.141592f);
Same about PI.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +	public void SetIMUMountingRotation(float rad, IMUTracker imu, Tracker t){ // Sets the mounting rotation (rad) of a given imu tracker and saves it.
Function names start with lower case.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +	public void GetIdle(){ // Gets the orientation of the first pose for each tracker one by one.
Please format your code:
- Function names start with lower case
- Space before `{`
- Function comments go on top of the function in JavaDoc stype:
```
/**
  * Gets the orientation of the first pose for each tracker one by one.
  **/
```
- Empty line between functions

Please, just use formatter.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +	public void CalibrateAllTrackers(){ // Called when the Calibrate Mounting button at top is pressed and calibrates the trackers one by one.
Same as the previous comment.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +	public void CalibrateTracker(Quaternion idleQuat, IMUTracker imu, Tracker tracker){
Same as the previous comment.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +		allTrackers = (FastList<Tracker>) server.getAllTrackers();
Don't cast to specific type, the type of returned varible may change in the future, you're shooting yourself in the leg. You also don't need `allTrackers` to be a member at all, nor for it to be FastList specifically. This doesn't get called all that often, and getAllTrackers() returns new object, why are you storing it at all?

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +		trackerOrientationIdle = new FastList<>();
Why are you recreating the object, instead of doing clear() on existing one?

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +			realTracker = ((ReferenceAdjustedTracker<? extends Tracker>) t).getTracker();
Please format yourr code.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +			realTracker = ((ReferenceAdjustedTracker<? extends Tracker>) t).getTracker();
Code format.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +		allTrackers = (FastList<Tracker>) server.getAllTrackers();
Same, why `allTrackers` is member variable?

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +		trackerNumber = 0;
Why is it member variable and not local variable?

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +		if(!endOnly){ // Rotates squat Quaternion to 90 degrees.
Formatting.

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +				else{
My eyes. Formatting!

2022-04-02 15:39 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +	private static float verticalOrientation(Quaternion quat) // Returns from 0 to 0.06666. 0.03333 = 90 degrees.
*sobbing*

2022-04-02 15:46 UTC, TheDevMinerTV requested changes

2022-04-02 15:46 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +	public float getMountingRotation() {
Please just put a newline in front of functions... (also on the end)

2022-04-02 16:57 UTC, TheDevMinerTV requested changes

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/VRServer.java
> +	public void captureIdleOrientations() {
formatting: add a newline in front

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/MountingCalibrationWindow.java
> +		pane.add(new EJBox(BoxLayout.LINE_AXIS) {
formatting: add a newline in front

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/MountingCalibrationWindow.java
> +
formatting: remove newline

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/MountingCalibrationWindow.java
> +	void finishDynamicCalibration() {
missing access specified (`public`, etc.)

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/MountingCalibration.java
> +
formatting: remove newline

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/TrackerConfig.java
> +		configNode.setProperty("rotation", mountingRotation);
formatting: add newline in front and after

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 16:57 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
formatting: remove spaces

2022-04-02 17:04 UTC, Louka3000 commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
Hey!!! Your Shift + Alt + F thing added those spaces!! ;-;

2022-04-02 18:58 UTC, Eirenliel commented on src/main/java/dev/slimevr/vr/trackers/IMUTracker.java
> +
That's no big deal.

2022-04-06 21:25 UTC, Louka3000 commented
After someone reported bad calibration, I found out that the calibration will be off if the tracker is tilted to the side.
Need to fix this somehow before merging into `main`

2022-04-07 01:52 UTC, Louka3000 commented
Update: I don't think the way I'm doing it is good enough after all.
Might need to use HMD rotation. Problem is that the HMD yaw and trackers' yaw are all different.
So it needs to align tracker yaw with HMD from the 2 poses.

What my code currently does (which is stupid) is:
        /* 
	 * Yaw of IMUs is random (determined when booting up), but pitch and roll is absolute.
	 * This rotates tracker to exactly 90 degrees and takes the roll. This is indeed the
	 * equivalent of the yaw we need but absolute.
	 */

2022-04-11 15:06 UTC, Eirenliel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mounting calibration](https://trello.com/c/35OHV2tW/9-mounting-calibration)

2022-04-29 21:40 UTC, Louka3000 commented
Created a new branch: https://github.com/Louka3000/SlimeVR-Server/tree/mounting-calibration
Will clean up my code and make it work with the most recent commits and create a new PR once we got the math figured out and all :3

2022-04-29 21:40 UTC, closed without merging