Format all files based on .editorconfig
SlimeVR/SlimeVR-Server pull request #162
Opened 2022-04-27 19:41 UTC by loucass003

2022-04-27 20:12 UTC, TheDevMinerTV requested changes

2022-04-27 20:12 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/bridge/BridgeThread.java
> +public @interface BridgeThread {
```suggestion
public @interface BridgeThread {}
```

2022-04-27 20:12 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/bridge/BridgeThread.java
> +}
```suggestion
```

2022-04-27 20:12 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/bridge/BridgeThread.java
> +
```suggestion
```

2022-04-27 20:12 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/NetworkProtocol.java
> +
```suggestion
```

2022-04-27 21:20 UTC, TheDevMinerTV requested changes
Please apply this and reformat <3

2022-04-27 21:20 UTC, TheDevMinerTV commented on .editorconfig
> +end_of_line = crlf
```suggestion
end_of_line = lf
```

2022-04-28 12:23 UTC, Eirenliel approved these changes

2022-04-28 12:32 UTC, merged