Implement devices in the protocol
SlimeVR/SlimeVR-Server pull request #205
Opened 2022-06-29 01:53 UTC by loucass003

Implement real devices in the protcol and fixed how synthetic trackers where listed
Add support for feeder app trackers in the protocol (needed the devices for that)

2022-06-29 02:40 UTC, Louka3000 approved these changes
Works fine after I tried to break it by doing weird stuff with the HMD role and feeder app controller and tracker.

2022-07-01 06:38 UTC, TheDevMinerTV requested changes
Just some style changes (why do you guys make your code look so squished?)

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/TrackersList.java
> +			if (tracker instanceof TrackerWithWireless) {
```suggestion

			if (tracker instanceof TrackerWithWireless) {
```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/TrackersList.java
> +			if (tracker instanceof TrackerWithWireless) {
```suggestion

			if (tracker instanceof TrackerWithWireless) {
```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/TrackersList.java
> +			if (tracker instanceof TrackerWithWireless) {
```suggestion

			if (tracker instanceof TrackerWithWireless) {
```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/TrackersList.java
> +				if (signal == -1) {
```suggestion

				if (signal == -1) {
```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/gui/TrackersList.java
>  			}
```suggestion
			}

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/platform/windows/WindowsNamedPipeBridge.java
>  		);
```suggestion
		);

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/protocol/DataFeedBuilder.java
> +		}
```suggestion
		}

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/Device.java
> +
```suggestion
```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +		IMUTracker imu = connection.getTracker(trackerId);
```suggestion

		IMUTracker imu = connection.getTracker(trackerId);

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +			connection.getTrackers().add(imu);
```suggestion

			connection.getTrackers().add(imu);
```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +								Iterator<IMUTracker> iterator = conn.getTrackers().iterator();
```suggestion
								Iterator<IMUTracker> iterator = conn.getTrackers().iterator();

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +								Iterator<IMUTracker> iterator = conn.getTrackers().iterator();
```suggestion
								Iterator<IMUTracker> iterator = conn.getTrackers().iterator();

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				tracker = connection.getTracker(rotationPacket.getSensorId());
```suggestion
				tracker = connection.getTracker(rotationPacket.getSensorId());

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				tracker = connection.getTracker(rotationData.getSensorId());
```suggestion
				tracker = connection.getTracker(rotationData.getSensorId());

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				tracker = connection.getTracker(magAccuracy.getSensorId());
```suggestion
				tracker = connection.getTracker(magAccuracy.getSensorId());

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +						;
```suggestion

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				tracker = connection.getTracker(tap.getSensorId());
```suggestion
				tracker = connection.getTracker(tap.getSensorId());

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				tracker = connection.getTracker(error.getSensorId());
```suggestion

				tracker = connection.getTracker(error.getSensorId());

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +					Iterator<IMUTracker> iterator = connection.getTrackers().iterator();
```suggestion

				if (connection.getTrackers().size() > 0) {
					Iterator<IMUTracker> iterator = connection.getTrackers().iterator();

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				if (connection.getTrackers().size() > 0) {
```suggestion

				if (connection.getTrackers().size() > 0) {

```

2022-07-01 06:38 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
>  				if (tracker == null)
```suggestion

				if (tracker == null)
```

2022-07-01 06:44 UTC, loucass003 commented
> Just some style changes (why do you guys make your code look so squished?)

I havent changed the indent of the original code. If you wat to change that i think i would have to be a separate pr.

2022-07-01 06:46 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +						;
da hecc

2022-07-01 06:51 UTC, TheDevMinerTV commented
Reduced my suggestions to code you've added.

2022-07-01 06:59 UTC, TheDevMinerTV requested changes

2022-07-01 06:59 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/platform/windows/WindowsNamedPipeBridge.java
> +		device.getTrackers().add(tracker);
```suggestion

		device.getTrackers().add(tracker);
```

2022-07-01 06:59 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/protocol/DataFeedBuilder.java
> +		HardwareInfo.addFirmwareVersion(fbb, nameOffset);
```suggestion
		HardwareInfo.addFirmwareVersion(fbb, nameOffset);

```

2022-07-01 06:59 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/DeviceManager.java
> +
```suggestion
```

2022-07-01 06:59 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +				if (connection.getTrackers().size() > 0) {
```suggestion

				if (connection.getTrackers().size() > 0) {
```

2022-07-01 07:05 UTC, TheDevMinerTV requested changes
minor nitpicking, after this I'm done :D

2022-07-01 07:05 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/protocol/DataFeedBuilder.java
> +			HardwareStatus.addTps(fbb, (int) ((TrackerWithTPS) tracker).getTPS());
```suggestion
			HardwareStatus.addTps(fbb, (int) ((TrackerWithTPS) tracker).getTPS());

```

2022-07-01 07:05 UTC, TheDevMinerTV commented on src/main/java/dev/slimevr/vr/trackers/udp/TrackersUDPServer.java
> +							);
```suggestion
							);

```

2022-07-01 07:20 UTC, TheDevMinerTV approved these changes

2022-07-03 21:57 UTC, Eirenliel approved these changes

2022-07-03 21:57 UTC, merged