Fix tracker rotations breaking gui
SlimeVR/SlimeVR-Server pull request #327
Opened 2022-11-30 23:28 UTC by Louka3000

:FA_FoxetteAngy: https://github.com/SlimeVR/SlimeVR-Server/pull/307

2022-11-30 23:35 UTC, TheDevMinerTV approved these changes

2022-11-30 23:57 UTC, Eirenliel commented on gui/src/components/tracker/TrackersTable.tsx
> +        {`${rot.pitch.toFixed(0)} / ${rot.yaww.toFixed(0)} / ${rot.roll.toFixed(
is it suppoed to be `yaww` not `yaw`?

2022-12-01 00:07 UTC, Louka3000 commented on gui/src/components/tracker/TrackersTable.tsx
> +        {`${rot.pitch.toFixed(0)} / ${rot.yaww.toFixed(0)} / ${rot.roll.toFixed(
ooops

2022-12-01 00:08 UTC, Louka3000 commented on gui/src/components/tracker/TrackersTable.tsx
> +        {`${rot.pitch.toFixed(0)} / ${rot.yaww.toFixed(0)} / ${rot.roll.toFixed(
fixed

2022-12-01 00:13 UTC, loucass003 approved these changes

2022-12-02 20:25 UTC, ButterscotchV approved these changes

2022-12-03 03:28 UTC, ButterscotchV requested changes
This reports rotation in radians, not degrees, please convert to degrees for the display :3

2022-12-03 04:55 UTC, ButterscotchV approved these changes

2022-12-03 06:12 UTC, merged