Fix page not opening
SlimeVR/SlimeVR-Server pull request #359
Opened 2022-12-10 14:13 UTC by macluxHD

The page opens now when pressing "I'm having trouble connecting!"  Button, even if typedState is undefiend.

Fixes #345

2022-12-10 22:01 UTC, loucass003 requested changes
This is not enough. We need the button in the wifi window to set the state with a port
Auto for now will be best

2022-12-11 01:18 UTC, macluxHD commented
The Button now sets the SerialPort State to Auto

2022-12-11 14:36 UTC, Eirenliel approved these changes

2022-12-13 08:39 UTC, loucass003 approved these changes

2022-12-13 16:14 UTC, merged