Finished relicense
SlimeVR/SlimeVR-Server pull request #428
Opened 2022-12-26 23:43 UTC by TheButlah

2022-12-27 18:30 UTC, Eirenliel requested changes

2022-12-27 18:30 UTC, Eirenliel commented on README.md
> +([LICENSE-MIT] and [LICENSE-APACHE]). These licenses are the copyright of the SlimeVR
This is worded wrong.

```suggestion
([LICENSE-MIT] and [LICENSE-APACHE]). The software is the copyright of the SlimeVR
```

2022-12-27 18:30 UTC, Eirenliel commented on README.md
> +([LICENSE-MIT] and [LICENSE-APACHE]). These licenses are the copyright of the SlimeVR
This is worded wrong.

```suggestion
([LICENSE-MIT] and [LICENSE-APACHE]). The software is the copyright of the SlimeVR
```

2023-01-03 17:40 UTC, Eirenliel commented
@TheButlah 🥺

2023-01-03 21:42 UTC, TheButlah commented
oops 
will fix after work
you can also edit the PR directly

2023-01-06 19:06 UTC, TheButlah commented on LICENSE-APACHE
> +   Copyright 2020 SlimeVR Contributors
```suggestion
   Copyright 2022 Eiren Rain and SlimeVR Contributors
```

2023-01-06 19:07 UTC, TheButlah commented on LICENSE-MIT
> +Copyright (c) 2020 SlimeVR Contributors
```suggestion
Copyright (c) 2020 Eiren Rain and SlimeVR Contributors
```

2023-01-06 19:08 UTC, TheButlah commented on README.md
> +  Contributors` part of the license. It is insufficient to use a generic MIT
```suggestion
  [LICENSE-APACHE] files from SlimeVR. This includes the `Copyright (c) 2020 Eiren Rain
  and SlimeVR Contributors` part of the license. It is insufficient to use a generic MIT
```

2023-01-06 20:26 UTC, Eirenliel approved these changes

2023-01-06 20:26 UTC, merged