Offsets refactor + add chest offset
SlimeVR/SlimeVR-Server pull request #443
Opened 2023-01-03 06:09 UTC by Louka3000

- Refactors the offsets to be linear in server, protocol and GUI.
- Fix some skeleton default rotation for hands
- Add a chest offset and remove the elbow offset

Protocol PR: https://github.com/SlimeVR/SolarXR-Protocol/pull/86

2023-01-03 08:16 UTC, Louka3000 commented
For GUI, I kinda like having the raw offsets, but that will require translation changes.
Most people won’t mess with manual body proportions, so trying to make it user friendly, even if it won’t ever be, is a loss. I would rather make it clear and precise.
What do you think @ImUrX @loucass003

2023-01-03 17:08 UTC, Eirenliel commented
Please rebase

2023-01-03 20:40 UTC, Louka3000 commented
Done @Eirenliel

2023-01-05 14:14 UTC, Eirenliel approved these changes

2023-01-05 14:16 UTC, Eirenliel commented
cannot webase in dithub.dew 🥺

2023-01-05 16:35 UTC, ImUrX requested changes
You shouldn't machine translate keys imo and should also add missing strings (no strict requirements on the last one but it should be done tbh)

2023-01-05 19:47 UTC, Louka3000 commented
I didn’t machine translate anything?

2023-01-05 20:13 UTC, Louka3000 commented
fixing missing keys tho

2023-01-05 20:55 UTC, ImUrX approved these changes

2023-01-06 02:15 UTC, Louka3000 commented on server/src/main/java/dev/slimevr/config/CurrentVRConfigConverter.java
> +			}
absolutely

2023-01-06 02:17 UTC, Louka3000 commented on gui/src/components/onboarding/pages/body-proportions/autobone-steps/VerifyResults.tsx
> +            <div></div>
I wanted to add some space and I hate HTML okay ;-;

2023-01-06 02:24 UTC, Louka3000 commented on gui/src/components/onboarding/pages/body-proportions/autobone-steps/VerifyResults.tsx
> +            <div></div>
Okay I found out how to do it properly

2023-01-06 02:38 UTC, Louka3000 commented on server/src/main/java/dev/slimevr/vr/processor/skeleton/HumanSkeleton.java
> +							(height * BodyProportionError.proportionLimits[2].getTargetRatio())
Done

2023-01-06 02:43 UTC, ButterscotchV approved these changes

2023-01-08 14:14 UTC, Eirenliel approved these changes

2023-01-08 14:14 UTC, merged