Update Chinese translations
SlimeVR/SlimeVR-Server pull request #459
Opened 2023-01-06 12:46 UTC by Disappear9

2023-01-06 18:37 UTC, ImUrX requested changes

2023-01-06 18:37 UTC, ImUrX commented on gui/public/i18n/zh-Hans/translation.ftl
> +tracker_selection_menu-LEFT_CONTROLLER = { -tracker_selection-part } 左控制器？
You can remove the space after the ``}`` if you want :p

2023-01-06 18:37 UTC, ImUrX commented on gui/public/i18n/zh-Hans/translation.ftl
> +onboarding-connect_tracker-connected_trackers = { $amount } 个追踪器已连接
Don't you want to say a different message when there are no trackers connected?

2023-01-06 18:37 UTC, ImUrX commented on gui/public/i18n/zh-Hans/translation.ftl
> +settings-general-gesture_control-taps = { $amount } 次敲击
```suggestion
settings-general-gesture_control-taps = { $amount ->
    *[other] { $amount }次敲击
}
```

2023-01-06 18:37 UTC, ImUrX commented on gui/public/i18n/zh-Hans/translation.ftl
> +onboarding-assign_trackers-assigned = { $assigned } / { $trackers } 个追踪器已分配
```suggestion
onboarding-assign_trackers-assigned = { $assigned }/{ $trackers } 个追踪器已分配
```

2023-01-06 18:37 UTC, ImUrX commented on gui/public/i18n/zh-Hans/translation.ftl
> +onboarding-automatic_proportions-recording-timer =  剩余 { $time } 秒
```suggestion
onboarding-automatic_proportions-recording-timer =  剩余{ $time }秒
```

2023-01-07 07:04 UTC, ImUrX approved these changes

2023-01-08 14:12 UTC, Eirenliel approved these changes

2023-01-08 14:12 UTC, merged