Spanish new lines translated
SlimeVR/SlimeVR-Server pull request #473
Opened 2023-01-10 21:05 UTC by MaxEvil47

Translated the new lines to Latin American Spanish.
All feedback and suggestions are welcome.

2023-01-14 08:40 UTC, ImUrX requested changes
Voy a preguntar en el Discord sobre la traduccion de drift

2023-01-14 08:40 UTC, ImUrX commented on gui/public/i18n/es-419/translation.ftl
> +} conectados
podes sacar la parte de ``conectados`` y poner conectado en ``[one]``

2023-01-14 08:40 UTC, ImUrX commented on gui/public/i18n/es-419/translation.ftl
> +} asignados
lo mismo aca

2023-01-14 08:40 UTC, ImUrX commented on gui/public/i18n/es-419/translation.ftl
> +tracker_selection_menu-HEAD = cabeza?
Esto esta mal, el mensaje va a ser ``cabeza?`` literalmente. Tendrias que poner ``¿Qué sensor asignar a tu cabeza?`` o si no queres hacer copy+paste en todo, podes usar ``{ -tracker_selection-part }`` asi no te repetis

2023-01-17 04:58 UTC, ImUrX requested changes

2023-01-17 04:58 UTC, ImUrX commented on gui/public/i18n/es-419/translation.ftl
> +    Compensa la desviación de los sensores aplicando una rotación inversa.
Habla de la desviación en el eje ``yaw``, que proviene de los ejes del avion. Yo personalmente solo lo conozco como ``yaw`` pero en español se le dice ``guiñada`` o tambien lo podes llamar eje vertical.
Pero no compensa por la desviacion de todos los ejes del sensor!

2023-01-17 04:58 UTC, ImUrX commented on gui/public/i18n/es-419/translation.ftl
>  onboarding-assign_trackers-assigned = { $assigned } of { $trackers ->
Mira desde el ``=``, pone la variable $assigned y despues hay un ``of`` que es texto.
Osea justo ahora se ve asi la traduccion: ``1 of 1 sensor asignado``

2023-01-17 05:07 UTC, ImUrX approved these changes

2023-01-18 19:20 UTC, Eirenliel approved these changes

2023-01-18 19:20 UTC, merged