Let code owners merge PRs
SlimeVR/SlimeVR-Server pull request #479
Opened 2023-01-16 23:38 UTC by Eirenliel

Adds CODEOWNERS file and assigns some codeownders. The codeowners can merge PRs by posting `LGTM` if all checks passed using https://github.com/marketplace/actions/code-owner-self-merge?version=1.6.5

2023-01-16 23:39 UTC, Eirenliel commented
suggestions for code owners are welcomed

2023-01-16 23:46 UTC, Louka3000 commented
I think @loucass003 should be code owner for server config since he wrote all of it: `server/src/main/java/dev/slimevr/config`

and I'd like to be code owner on skeleton stuff: `server/src/main/java/dev/slimevr/vr/processor` (which is changing to `server/src/main/java/dev/slimevr/tracking/processor` with my refactor...) and tracker filtering: `server/src/main/java/dev/slimevr/filtering`

2023-01-16 23:50 UTC, Eirenliel commented
👍

2023-01-16 23:50 UTC, TheButlah commented on .github/CODEOWNERS
> +server/src/main/java/dev/slimevr/config/ @loucass003
```suggestion
server/src/main/java/dev/slimevr/config/ @loucass003

```

2023-01-16 23:50 UTC, TheButlah commented on .github/workflows/codeowners-merge.yml
> +          if_no_maintainers_assign: '@Eirenliel @ButterscotchV'
```suggestion
          if_no_maintainers_assign: '@Eirenliel @ButterscotchV'
```

2023-01-16 23:54 UTC, Louka3000 submitted a review, later dismissed

2023-01-17 01:22 UTC, ButterscotchV approved these changes

2023-01-17 04:29 UTC, ImUrX requested changes

2023-01-17 04:29 UTC, ImUrX commented on .github/CODEOWNERS
> +
```suggestion

# Rust part of the GUI
/gui/src-tauri/ @ImUrX @TheButlah 

```

2023-01-17 16:51 UTC, Louka3000 commented
_Actually, why does Butter get full merge perms on all of /server, shouldn’t I also do… I even wrote more code :nya_a:_

2023-01-17 17:47 UTC, Louka3000 commented
Important stuff from Discord:

With the current way it is, I won’t be able to do anything except hotfixes to these specific packages, since implementing anything new would require config or protocol/rpc changes. 

So, for example, even if 99% of my code in a PR to add a new skeleton config toggle is in the skeleton package, if it has a line of code in RPCSettingsHandler to make it work with the protocol, it’d absolutely need Butter or Eiren to merge…

Something like https://github.com/marketplace/actions/auto-request-review would allow to automatically request reviews when a PR touches a certain part of the code.
I propose Butter and I have merge perms for server, and moving the specific perms (Autobone, BVH, Skeleton, OSC and Filtering) to auto-reviews.

Btw, having perms to merge `gui/src/components/settings` would be nice too, since I’ve been touching that part a lot

2023-01-17 17:56 UTC, Louka3000 reviewed
^

2023-01-17 20:15 UTC, Eirenliel commented
> The problem thus is that my codeowner perms are useless except for small hotfixes inside given packages, as any change that brings new stuff to the server will need code change outside of those packages.

We were talking about letting you to merge language changes in the first place. This system is a workaround from giving permissions to merge on everything. I'm trying to make a "well you can sort at least some of it without me and i'll still sleep well" kind of system.

2023-01-17 20:30 UTC, Louka3000 commented
My original proposal was just to be able to merge on x approving reviews.
Here, you’re giving Butter ownership of all server code, which means we could already merge full-fledged features or substantial code changes, but why only Butter? Feels unfair to me considering most recent server code is mine…

2023-01-18 20:37 UTC, Louka3000 approved these changes

2023-01-18 23:07 UTC, Eirenliel commented
> With the current way it is, I won’t be able to do anything except hotfixes to these specific packages, since implementing anything new would require config or protocol/rpc changes.

You shouldn't review and merge your own PRs either way. This is for when someone else changes your code, you can be an authority on merging it. That said, even then I want a policy that thrid eyes should look at it first.

2023-01-18 23:42 UTC, Eirenliel commented
I added a bunch of owners and rules and removed the system with LGTM, instead @TheButlah, @Louka3000, I and @ButterscotchV are now maintainers and can merge if branch protection rules are satisfied. Which I changed to require 2 reviews and code owner reviews.

2023-01-19 00:04 UTC, Louka3000 commented
From Discord:
- All code owners for the PR must approve (forced by GH)
- Need at least 2 total approving reviews by anyone in the GH contributor team (forced by GH)
- Need checks to pass and no change requests (forced by GH)
- No change request for a day (not forced by GH)

2023-01-19 00:04 UTC, Louka3000 approved these changes

2023-01-19 00:19 UTC, ImUrX approved these changes

2023-01-19 02:36 UTC, TheButlah approved these changes

2023-01-19 02:41 UTC, ButterscotchV approved these changes

2023-01-21 21:06 UTC, merged