Translating new lines in dutch
SlimeVR/SlimeVR-Server pull request #490
Opened 2023-01-18 20:23 UTC by Vyolex

Translating new lines that got introduced in #450.

2023-01-18 20:29 UTC, Vyolex commented
Line 123, 124 and 125 not being changed is intentional.

Temp. is a valid abbreviation for "Temperatuur"
Accel. is a valid abbreviation for "Acceleratie"

2023-01-18 21:49 UTC, ImUrX requested changes
``settings-general-tracker_mechanics-amount`` is now ``settings-general-tracker_mechanics-filtering-amount``

2023-01-18 21:49 UTC, ImUrX commented on gui/public/i18n/nl/translation.ftl
>  overlay-is_mirrored_label = Overlay weergeven als spiegel
```suggestion
widget-overlay-is_visible_label = Overlay in SteamVR weergeven
widget-overlay-is_mirrored_label = Overlay weergeven als spiegel
```

2023-01-19 08:24 UTC, Vyolex commented
> `settings-general-tracker_mechanics-amount` is now `settings-general-tracker_mechanics-filtering-amount`

should be fixed now

2023-01-20 02:00 UTC, Louka3000 approved these changes

2023-01-20 04:20 UTC, ImUrX approved these changes

2023-01-20 06:04 UTC, merged