Add linux metadata
SlimeVR/SlimeVR-Server pull request #506
Opened 2023-01-24 05:23 UTC by ImUrX

- Added an svg because linux supports svg icons.
- Added [appstream](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) metadata for information about the application
- Added a .desktop file for usage in installations

2023-01-24 18:27 UTC, TheButlah approved these changes

2023-01-24 18:27 UTC, TheButlah commented
Note that this PR licenses the metatdata file under CC0

2023-01-26 03:23 UTC, ttennial94 approved these changes

2023-01-26 15:59 UTC, ButterscotchV requested changes

2023-01-26 15:59 UTC, ButterscotchV commented on dev.slimevr.SlimeVR.metainfo.xml
> +      <image>https://media.discordapp.net/attachments/818062236492759050/1044722428951134310/image.png</image>
I don't like this linking to Discord, can we just put the image on GitHub in this repo and link to it instead?

2023-01-26 15:59 UTC, ButterscotchV commented on dev.slimevr.SlimeVR.metainfo.xml
> +  <url type="faq">https://docs.slimevr.dev/server-setup/slimevr-setup.html</url>
Is this the best link we have for this? I imagine an alternative could be https://docs.slimevr.dev/slimevr101.html.

2023-01-27 16:55 UTC, ButterscotchV approved these changes
<3

2023-01-27 17:52 UTC, Eirenliel approved these changes

2023-01-27 17:52 UTC, merged