Fix translations
SlimeVR/SlimeVR-Server pull request #513
Opened 2023-01-25 03:31 UTC by ImUrX

2023-01-25 03:40 UTC, Louka3000 requested changes
Since there's no difference between singular and plural, you could just copy from the plural and replace the `{ $trackers/time }` by `1`

2023-01-25 03:40 UTC, Louka3000 commented on gui/public/i18n/vi/translation.ftl
> +    [one] 1 tap
```suggestion
    [one] 1 lần
```

2023-01-25 03:40 UTC, Louka3000 commented on gui/public/i18n/vi/translation.ftl
> +    [one] 1 second
```suggestion
    [one] còn lại 1 giây
```

2023-01-25 03:41 UTC, ImUrX commented
I kept the strings untranslated because they are not gonna get triggered

2023-01-25 03:45 UTC, Louka3000 approved these changes
Indeed :o

2023-01-25 09:29 UTC, TheDevMinerTV requested changes
Remove the German translations, we have  a PR already.

2023-01-26 08:47 UTC, TheDevMinerTV approved these changes

2023-01-26 16:01 UTC, ButterscotchV approved these changes

2023-01-26 16:10 UTC, merged