Lots of misc gui fixes
SlimeVR/SlimeVR-Server pull request #516
Opened 2023-01-25 07:18 UTC by ImUrX

- Fixes #440 and #510
- Remove unneeded dependencies like ``fs-nextra`` and ``dotenv``
- Fixed flag emojis not working in Linux (**requires testing on Windows!**)
- ``Typography`` supports whitespace now specification which is nice for newline detection in translations

2023-01-25 07:24 UTC, ImUrX commented
Example images:
![neck](https://user-images.githubusercontent.com/3698237/214503699-82d54f48-6b6e-45d1-985d-cabe72e406ee.png)
![serial](https://user-images.githubusercontent.com/3698237/214503752-b53813d7-b840-4f3b-9d74-4b7ce1e1d5ff.png)

2023-01-25 11:38 UTC, Eirenliel approved these changes

2023-01-26 00:54 UTC, Louka3000 requested changes
You're only making the neck warning appear in the "manage all trackers" tracker assignment menu. Please make it appear in the individual tracker assignment popup as well (when you click on a tracker and assign its body position from there)

2023-01-26 06:47 UTC, Louka3000 approved these changes
I added furry and french translation

2023-01-26 14:32 UTC, ImUrX commented
last commit made position be able to be converted to cm precision

2023-01-26 16:21 UTC, ButterscotchV requested changes

2023-01-26 16:21 UTC, ButterscotchV commented on gui/src/components/onboarding/NeckWarningModal.tsx
> +    setShowed(false);
Misspelled "Showed" should be "Shown" (Not blocking merge for this).

2023-01-26 16:21 UTC, ButterscotchV commented on gui/src/components/onboarding/NeckWarningModal.tsx
> +            <WarningBox>Warning!</WarningBox>
`Warning!` should be translated.

2023-01-26 16:21 UTC, ButterscotchV commented on gui/src/components/settings/pages/Serial.tsx
> +          <WarningBox>Warning!</WarningBox>
Same as last comment about this, `Warning!` should be translated.

2023-01-29 16:57 UTC, merged