Fix lang select being too long
SlimeVR/SlimeVR-Server pull request #571
Opened 2023-02-09 19:49 UTC by ImUrX

Added tab support on the dropdown component and limited it to 50vh of ``max-height``, fixed scrollbar color and added css scrollbar properties (only work with Firefox).
Also added some decorations and an alignment option on it

2023-02-09 22:58 UTC, Louka3000 requested changes
Scrolling has weird behaviour... It sometimes allows you to scroll (notably when the select scrollbar is at the top or bottom), and sometimes not, and it's annoying ;-;
https://cdn.discordapp.com/attachments/1044838643522601031/1073376998409383957/slimevr_GaXXkGBjxv.mp4

2023-02-09 23:05 UTC, ImUrX commented
You want me to fix a browser problem :sob:, I will see what I can do

2023-02-09 23:08 UTC, Louka3000 commented
Browsers suck, let's go back to TVs and phones

2023-02-10 04:12 UTC, Louka3000 approved these changes

2023-02-10 23:14 UTC, ButterscotchV approved these changes

2023-02-12 11:33 UTC, loucass003 approved these changes

2023-02-12 14:25 UTC, merged