Fix trackers overflow in dev mode
SlimeVR/SlimeVR-Server pull request #575
Opened 2023-02-10 05:23 UTC by Louka3000

2023-02-10 06:21 UTC, ImUrX requested changes

2023-02-10 06:21 UTC, ImUrX commented on gui/src/components/home/Home.tsx
> +        <div className="px-2 pt-5 justify-center overflow-y-scroll overflow-x-auto">
```suggestion
        <div className="px-2 pt-5 overflow-y-scroll overflow-x-auto">
```
Seeing the child element, it's just another div that is also a flex box.

2023-02-10 06:29 UTC, ImUrX approved these changes

2023-02-11 23:00 UTC, ButterscotchV approved these changes

2023-02-12 17:56 UTC, merged