fix row height
SlimeVR/SlimeVR-Server pull request #601
Opened 2023-02-19 22:36 UTC by loucass003

2023-02-19 23:14 UTC, ImUrX requested changes
fix the eslint problem, but seems fine

2023-02-19 23:16 UTC, loucass003 commented
No ? as long as the git lint config does not match the local files gui config. i wont follow it. And i wont fix it in this pr this is not the purpose of it

2023-02-19 23:19 UTC, ImUrX requested changes

2023-02-19 23:19 UTC, ImUrX commented on gui/src/components/tracker/TrackersTable.tsx
> +  TrackerStatus as TrackerStatusEnum
```suggestion
  TrackerStatus as TrackerStatusEnum,
```

2023-02-19 23:21 UTC, loucass003 commented on gui/src/components/tracker/TrackersTable.tsx
> +  TrackerStatus as TrackerStatusEnum
no

2023-02-19 23:25 UTC, ImUrX approved these changes

2023-02-20 05:09 UTC, ButterscotchV approved these changes

2023-02-22 21:46 UTC, merged