server: Log resets from all sources
SlimeVR/SlimeVR-Server pull request #604
Opened 2023-02-21 07:15 UTC by 0forks

Currently resets are not logged in all cases. This PR adds reset logging for tap detection and feeder app bridge, unifies reset log message.

This can be useful for tracking time between resets.

2023-02-22 20:37 UTC, Louka3000 requested changes
These logs are no longer needed, as they're just duplicated at that point and aren't useful.
Also I think we should move towards the "fast -> yaw" naming

2023-02-22 20:37 UTC, Louka3000 commented on server/src/main/java/dev/slimevr/Keybinding.java
>  				LogManager.info("[Keybinding] Reset pressed");
```suggestion
```

2023-02-22 20:37 UTC, Louka3000 commented on server/src/main/java/dev/slimevr/Keybinding.java
>  				LogManager.info("[Keybinding] Reset mounting pressed");
```suggestion
```

2023-02-22 20:37 UTC, Louka3000 commented on server/src/main/java/dev/slimevr/tracking/processor/skeleton/HumanSkeleton.java
> +		LogManager.info("Reset: quick (%s)".formatted(resetSourceName));
```suggestion
		LogManager.info("Reset: yaw (%s)".formatted(resetSourceName));
```

2023-02-23 04:14 UTC, ButterscotchV approved these changes

2023-02-23 05:01 UTC, Louka3000 approved these changes

2023-02-25 14:26 UTC, Eirenliel approved these changes

2023-02-25 14:28 UTC, Eirenliel commented
plz rebase 🥺

2023-02-26 12:18 UTC, merged