Improve setup wizard
SlimeVR/SlimeVR-Server pull request #639
Opened 2023-03-23 22:41 UTC by ImUrX

* Changed overlay of most buttons
* Added progress bar on provisioning for tracker
* Fixed some bugs like progress bars being remade every time and reset proportions on autobone having a countdown but no showing it

2023-03-25 21:43 UTC, Eirenliel commented
After https://github.com/SlimeVR/SlimeVR-Server/pull/636 conflicts need to be resolved + we need to take a look at the page together and maybe do some quick changes.

2023-03-25 22:16 UTC, Eirenliel approved these changes

2023-03-25 22:16 UTC, Eirenliel commented on gui/src/components/onboarding/SkipSetupWarningModal.tsx
> +              <b>Warning:</b> The setup is needed for good tracking, this is
I10n missing?

2023-03-25 22:52 UTC, ImUrX commented on gui/src/components/onboarding/SkipSetupWarningModal.tsx
> +              <b>Warning:</b> The setup is needed for good tracking, this is
Nah, its ``<Localized>``

2023-03-28 22:31 UTC, ButterscotchV requested changes

2023-03-28 22:31 UTC, ButterscotchV commented on gui/src/hooks/app.ts
> +  console.log(bones);
Forgotten debug code?
```suggestion
```

2023-03-28 22:40 UTC, ButterscotchV commented
I'd also like to report from some quick testing, you can still click on mounting positions even when they're invisible. As you can see in my first screenshot, I have no trackers connected. In my second screenshot, I've clicked on the invisible tracker mounting assignment position button and it shows the GUI. After clicking on one, it is no longer clickable.

![image](https://user-images.githubusercontent.com/5095026/228382590-66685ec1-4a21-456a-8c15-d9ca5d08d741.png)
![image](https://user-images.githubusercontent.com/5095026/228382621-3c2640a4-54bb-446b-8cf0-d71b497f08ec.png)

2023-03-29 01:49 UTC, Louka3000 requested changes
- In the warning popup prompting the user to do the setup when attempting to skip it, I think the "confirm" option (Skip setup) should be in purple, and the "cancel" option (Continue setup) should be in gray. It's confusing...
- Clicking "Manual calibration" in the Body proportions tab, outside of the initial setup, brings the user to the setup wizard. Same with the Mounting calibration tab.

2023-03-29 01:49 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +    this is required if this is your first time using SlimeVR.
```suggestion
    it is required if it is your first time using SlimeVR.
```

2023-03-30 14:51 UTC, ImUrX commented on gui/src/components/onboarding/SkipSetupWarningModal.tsx
> +              variant="tiertiary"
this will get fixed in another PR tbh

2023-03-30 14:55 UTC, ImUrX commented on gui/src/components/widgets/SkeletonVisualizerWidget.tsx
> +})();
No? How can I know the hierarchy of bones dynamically?

2023-03-30 15:14 UTC, Louka3000 commented
Having a confirmation popup is already doing that.
The “confirm” option should always be the one that’s highlighted imo

2023-03-31 14:03 UTC, merged