Improve vrchat osctrackers text
SlimeVR/SlimeVR-Server pull request #675
Opened 2023-04-16 23:02 UTC by Louka3000

2023-04-16 23:08 UTC, ImUrX approved these changes

2023-04-22 22:58 UTC, ButterscotchV requested changes
Looks good, but I think it could be specified that you don't *need* to be using Quest Standalone.

2023-04-22 22:58 UTC, ButterscotchV commented on gui/public/i18n/en/translation.ftl
> +    tracker data for FBT without SteamVR (Quest standalone).
```suggestion
    tracker data for FBT without SteamVR (ex. Quest standalone).
```

2023-04-23 19:52 UTC, ButterscotchV approved these changes

2023-04-24 21:31 UTC, merged