Convert UDP Server stuff to Kotlin
SlimeVR/SlimeVR-Server pull request #683
Opened 2023-04-22 01:11 UTC by ImUrX

Ignore the branch name >~>, should I remove any of the remaining deprecated objects?

2023-04-22 23:01 UTC, ButterscotchV commented
This PR has a large number of formatting changes that will cause *many* conflicts with almost all of the open PRs based off of `tracker-rewrite`, please consider that before merging.

2023-04-22 23:35 UTC, ImUrX commented
fixed :roll_eyes:

2023-04-23 00:00 UTC, ButterscotchV commented
Noice, you can make format changes in a separate PR to make it easier to manage, thankyu <3

2023-04-24 14:27 UTC, Eirenliel requested changes

2023-04-24 16:18 UTC, ImUrX commented on server/src/main/java/dev/slimevr/tracking/trackers/udp/SensorTap.kt
> +sealed interface SensorSpecificPacket {
hm, you are right, i will fix that.

2023-04-28 03:16 UTC, 0forks commented
Uri asked for a review, I can't add anything objective other than it works, I've tested with the actual trackers and owotrack.

Personally I find packet definitions in a single file instead of 20 easier to navigate, but the final word is on the maintainers anyway.

2023-05-17 12:16 UTC, ImUrX commented
Ready for review & merge

2023-05-17 12:18 UTC, Eirenliel approved these changes

2023-05-17 12:18 UTC, merged