Add more tutorials on setup
SlimeVR/SlimeVR-Server pull request #696
Opened 2023-05-23 18:45 UTC by ImUrX

* Fix calibration tutorial using a PNG, now its an SVG (cooler)
* Add a how to put your tracker tutorial
* Add reset tutorial

2023-05-29 16:18 UTC, Eirenliel requested changes

2023-05-29 16:18 UTC, Eirenliel commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial = How to prepare the slime before putting it on
```suggestion
onboarding-assignment_tutorial = How to prepare Slime Tracker before putting it on
```

2023-05-29 16:18 UTC, Eirenliel commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial-first_step = 1. Place a body part sticker (if you have) on the slime according to your choosing
```suggestion
onboarding-assignment_tutorial-first_step = 1. Place a body part sticker (if you have one) on the tracker according to your choosing
```

2023-05-29 16:18 UTC, Eirenliel commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial-second_step = 2. Put the straps on your slime and make the hook and loop side of the strap face in the following orientation:
```suggestion
onboarding-assignment_tutorial-second_step = 2. Attach the straps to your tracker, keeping the hook and loop side of the strap face in the following orientation:
```

2023-05-29 16:18 UTC, Eirenliel commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_proportions-description = Body proportions are used to know the measurements of your body, the main reason for why the need for this is because we only know the rotation of trackers
```suggestion
onboarding-choose_proportions-description = Body proportions are used to know the measurements of your body. It's required to calculate the trackers position.
```

2023-05-29 16:18 UTC, Eirenliel commented on gui/public/i18n/en/translation.ftl
> +    When proportions of your body don't match the ones saved, it will provoke stuff like sliding, mainly things that would be based on your body.
```suggestion
    When proportions of your body don't match the ones saved, your tracking precision will be worse and you will notice things like skating or sliding, or your body not matching your avatar well.
```

2023-06-01 00:12 UTC, Louka3000 requested changes

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +    This just fully resets the position and rotation of all trackers, it should fix most of your issues.
```suggestion
    You need to be standing for this (i-pose). There is a 3 seconds delay (configurable) before it actually happens.
    This fully resets the position and rotation of all your trackers. It should fix most issues.
```

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial = How to prepare Slime Tracker before putting it on
```suggestion
onboarding-assignment_tutorial = How to prepare a SlimeVR Tracker before putting it on
```

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial-done = I put stickers and straps
```suggestion
onboarding-assignment_tutorial-done = I put stickers and straps!
```

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial-second_step = 2. Attach the straps to your tracker, keeping the hook and loop side of the strap face in the following orientation:
```suggestion
onboarding-assignment_tutorial-second_step = 2. Attach the strap to your tracker, keeping the hook and loop side of the strap face in the following orientation:
```

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial-second_step-continuation = The hook and loop side in the extension should also be facing like this:
```suggestion
onboarding-assignment_tutorial-second_step-continuation = The hook and loop side for the extension should be in this orientation:
```

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_mounting-description = Mounting orientation corrects for the placement of the tracker on your body, for example; if your tracker is looking to the left side when putting it on, you
```suggestion
onboarding-choose_mounting-description = Mounting orientation corrects for the placement of trackers on your body.
```
The rest of the text should be in the Manul mounting menu.

2023-06-01 00:12 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_proportions-description = Body proportions are used to know the measurements of your body. It's required to calculate the trackers position.
```suggestion
onboarding-choose_proportions-description = Body proportions are used to know the measurements of your body. They're required to calculate the trackers' positions.
```

2023-06-01 00:15 UTC, ImUrX commented on gui/public/i18n/en/translation.ftl
> +onboarding-assignment_tutorial = How to prepare Slime Tracker before putting it on
```suggestion
onboarding-assignment_tutorial = How to prepare a Slime Tracker before putting it on
```

2023-06-01 00:19 UTC, Louka3000 approved these changes

2023-06-01 18:42 UTC, merged