Updates the recommended mounting method to manual
SlimeVR/SlimeVR-Server pull request #734
Opened 2023-06-16 14:39 UTC by Vyolex

Swaps the order of manual/automatic mounting, along with changing which method is recommended on the mounting selection screen until a better visualisation method is available.

Discussed in #723, we did decide to drop the warning in the GUI.

2023-06-16 14:46 UTC, ImUrX approved these changes

2023-06-20 02:47 UTC, Louka3000 requested changes

2023-06-20 02:47 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_mounting-auto_mounting-subtitle = If you know what you are doing
```suggestion
onboarding-choose_mounting-auto_mounting-subtitle = Experimental
```
This fits better and makes more sense imo

2023-06-20 11:09 UTC, Eirenliel approved these changes

2023-06-20 11:10 UTC, merged