Convert HumanSkeleton to Kotlin
SlimeVR/SlimeVR-Server pull request #783
Opened 2023-07-19 03:29 UTC by Louka3000

In preparation for https://github.com/SlimeVR/SlimeVR-Server/tree/offsets-rotations

2023-07-19 08:08 UTC, ButterscotchV requested changes

2023-07-19 08:08 UTC, ButterscotchV commented on server/core/src/main/java/dev/slimevr/tracking/processor/skeleton/Localizer.kt
> +		skeleton.computedHipTracker?.let { hip = it.position }
```suggestion
		var hip = skeleton.computedHipTracker?.position ?: Vector3.NULL
```

2023-07-19 08:08 UTC, ButterscotchV commented on server/core/src/main/java/dev/slimevr/tracking/processor/skeleton/Localizer.kt
> +		skeleton.headTracker?.let { rot = it.getRotation() }
This can be done with an elvis operator. I would suggest it but you didn't modify the last line lol, look at my last comment for reference.

2023-08-13 07:21 UTC, ButterscotchV approved these changes

2023-08-13 19:43 UTC, Stermere approved these changes

2023-08-26 22:36 UTC, ButterscotchV commented
Doesn't compile on CI, pls fix.

2023-08-30 21:28 UTC, Louka3000 commented
@ButterscotchV fixed

2023-08-31 22:08 UTC, ButterscotchV approved these changes

2023-08-31 23:19 UTC, merged