Fix tap to assign
SlimeVR/SlimeVR-Server pull request #795
Opened 2023-07-26 01:16 UTC by Stermere

Repopulates the array of tap detectors that tap to assign uses whenever new trackers are added.

2023-07-26 23:25 UTC, Louka3000 commented on server/core/src/main/java/dev/slimevr/tracking/processor/skeleton/Localizer.kt
> +			println(worldReference)
sus

2023-07-28 02:42 UTC, Louka3000 approved these changes
Finally works yay!

2023-07-28 16:41 UTC, Louka3000 requested changes
This breaks Autobone

```[SERVER] java.lang.NullPointerException: Cannot invoke "dev.slimevr.config.TapDetectionConfig.getSetupMode()" because "this.config" is null
[SERVER]     at dev.slimevr.tracking.processor.skeleton.TapDetectionManager.update(TapDetectionManager.java:129)
[SERVER]     at dev.slimevr.tracking.processor.skeleton.HumanSkeleton.updatePose(HumanSkeleton.java:568)
[SERVER]     at dev.slimevr.tracking.processor.HumanPoseManager.update(HumanPoseManager.java:369)
[SERVER]     at dev.slimevr.autobone.AutoBoneStep.updatePlayerCursors(AutoBoneStep.kt:60)
[SERVER]     at dev.slimevr.autobone.AutoBoneStep.setCursors(AutoBoneStep.kt:53)
```

2023-07-31 07:44 UTC, Louka3000 approved these changes

2023-07-31 12:25 UTC, Eirenliel approved these changes

2023-07-31 12:25 UTC, merged