fix upper chest mounting null
SlimeVR/SlimeVR-Server pull request #799
Opened 2023-07-28 17:27 UTC by Louka3000

for once this isn't my fault!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! *I believe*

2023-07-28 17:28 UTC, ImUrX requested changes

2023-07-28 17:28 UTC, ImUrX commented on gui/src/components/onboarding/pages/mounting/MountingSelectionMenu.tsx
> +import { UpperChestIcon } from '../../../commons/icon/UpperChestIcon';
```suggestion
```

2023-07-28 17:28 UTC, ImUrX approved these changes

2023-07-28 17:36 UTC, ImUrX approved these changes

2023-07-30 14:45 UTC, Eirenliel approved these changes

2023-07-30 14:45 UTC, merged