add import proportions button
SlimeVR/SlimeVR-Server pull request #811
Opened 2023-08-08 12:23 UTC by ImUrX

2023-08-10 18:14 UTC, Louka3000 requested changes
Fails on import

2023-08-12 22:18 UTC, Louka3000 approved these changes

2023-08-15 01:37 UTC, loucass003 commented on gui/src/components/onboarding/pages/body-proportions/ProportionsChoose.tsx
> +              }}
Put this in a function please

2023-08-26 22:05 UTC, ButterscotchV reviewed
I've looked at it and it looks fine to me, but I can't really say whether it's good or not

2023-09-02 19:35 UTC, loucass003 approved these changes
LGTM

2023-09-02 19:57 UTC, merged