Small GUI fixes, pt. 2
SlimeVR/SlimeVR-Server pull request #815
Opened 2023-08-10 22:32 UTC by ImUrX

* Should finally fix the status system having the unnamed tracker :3
* Added persistent advanced body parts

2023-08-11 15:45 UTC, Louka3000 requested changes
~~blocking this because the pre-commit hook is fucky on GH Desktop/Windows lol~~ good now

2023-08-12 04:58 UTC, Louka3000 approved these changes

2023-08-12 18:59 UTC, TheDevMinerTV requested changes

2023-08-12 18:59 UTC, TheDevMinerTV commented on .husky/pre-commit
yeet this

2023-08-12 18:59 UTC, TheDevMinerTV commented on package.json
> +    "husky": "^8.0.3",
yeet this

2023-08-12 19:45 UTC, TheDevMinerTV approved these changes
Mh fine

2023-08-15 01:34 UTC, loucass003 approved these changes
LGTM

2023-08-19 15:07 UTC, Eirenliel approved these changes

2023-08-19 15:24 UTC, Louka3000 approved these changes

2023-08-19 15:24 UTC, merged