Filter out !isSiteLocalAddress from addresses
SlimeVR/SlimeVR-Server pull request #847
Opened 2023-09-17 16:41 UTC by Louka3000

2023-09-17 18:56 UTC, ImUrX approved these changes

2023-09-17 18:58 UTC, ImUrX requested changes
a=

2023-09-17 18:58 UTC, ImUrX commented on server/core/src/main/java/dev/slimevr/tracking/trackers/udp/TrackersUDPServer.kt
> +		}.filterNotNull().map { InetSocketAddress(it, this.port) }.toList().filter { it.address.isSiteLocalAddress }
```suggestion
		}.filter { it?.isSiteLocalAddress }.map { InetSocketAddress(it, this.port) }.toList()
```

2023-09-17 19:09 UTC, ImUrX approved these changes

2023-09-18 01:20 UTC, ButterscotchV approved these changes

2023-09-18 01:23 UTC, merged