Force manual mounting on setup
SlimeVR/SlimeVR-Server pull request #852
Opened 2023-09-25 03:20 UTC by ImUrX

Many people that start using the app end up using automatic without understanding how to use it. So let's enforce the manual mounting on the first-time use

2023-10-08 05:42 UTC, ButterscotchV approved these changes

2023-11-10 23:49 UTC, ImUrX commented
I changed on how this works, and now we are using a modal for it as a warning sign

2023-11-11 00:02 UTC, loucass003 approved these changes

2023-11-12 02:54 UTC, ButterscotchV approved these changes
Looks fine, we should probably also do this for AutoBone, especially since you don't really even do a full reset before getting to that step in the setup wizard

2023-11-12 03:46 UTC, Louka3000 requested changes

2023-11-12 03:46 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +    automatic mounting?
```suggestion
onboarding-choose_mounting-manual_modal-title = Are you sure you want to do
    the automatic mounting calibration?
```

2023-11-12 03:46 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_mounting-manual_modal-description = <b>You should first try doing manual mounting</b>, automatic mounting is quite hard to get right in its poses and requires some practice.
```suggestion
onboarding-choose_mounting-manual_modal-description = <b>We recommend the manual mounting calibration for new users</b>, as the automatic mounting calibration's pauses can be hard to get right first and may require some practice.
```

2023-11-12 04:33 UTC, ImUrX commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_mounting-manual_modal-description = <b>You should first try doing manual mounting</b>, automatic mounting is quite hard to get right in its poses and requires some practice.
```suggestion
onboarding-choose_mounting-manual_modal-description = <b>We recommend the manual mounting calibration for new users</b>, as the automatic mounting calibration's poses can be hard to get right first and may require some practice.
```

2023-11-12 04:38 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-choose_mounting-manual_modal-description = <b>We recommend the manual mounting calibration for new users</b>, as the automatic mounting calibration's poses can be hard to get right first a
```suggestion
onboarding-choose_mounting-manual_modal-description = <b>The manual mounting calibration is recommended for new users</b>, as the automatic mounting calibration's poses can be hard to get right first and may require some practice.
```

2023-11-12 04:41 UTC, Louka3000 approved these changes
Lgtm, but didn’t check the code because it’s typescript

2023-11-12 04:48 UTC, merged