Prompt before closing SlimeVR when trackers are still connected
SlimeVR/SlimeVR-Server pull request #862
Opened 2023-09-30 02:19 UTC by Eric13246

Completed task #24

Users will be prompted to confirm if they want to close SlimeVR if trackers are still connected. This warning is also configurable in the app's settings.

2023-10-01 21:34 UTC, loucass003 requested changes
Please change the naming of CloseApp() to closeApp 
And move the function inside the component as a closure

Alse use braces on if statements

2023-10-18 21:17 UTC, loucass003 approved these changes

2023-10-18 21:18 UTC, loucass003 commented
> That should do it. By the way, are there any unit tests or integration tests that are required when adding features?

No we do not have unit test.
This pr is first gonna be sent as a release candidate, and we have a full process of test done manually to ensure no critical feature is broken

2023-11-01 04:01 UTC, ImUrX approved these changes

2023-11-03 02:46 UTC, merged