Llelievr/firmware tool
SlimeVR/SlimeVR-Server pull request #880
Opened 2023-10-18 23:29 UTC by loucass003

2024-10-08 17:07 UTC, ImUrX commented on .github/CODEOWNERS
this file got edited because its crlf originally for some reason

2024-10-10 14:40 UTC, ImUrX requested changes

2024-10-10 14:40 UTC, ImUrX commented on gui/.eslintrc.json
w-what happened to eslint

2024-10-10 14:42 UTC, ImUrX commented on gui/.eslintrc.json
oh it was me nvm

2024-10-10 15:42 UTC, ImUrX requested changes

2024-10-10 15:42 UTC, ImUrX commented on gui/src/components/commons/VerticalStepper.tsx
> +    <ol className="relative border-l border-gray-700 text-gray-400 ">
```suggestion
    <ol className="relative border-l border-gray-700 text-gray-400">
```

2024-10-14 18:11 UTC, ImUrX requested changes

2024-10-14 18:11 UTC, ImUrX commented on gui/src/components/firmware-tool/SelectFirmwareStep.tsx
> +  const showTirdParty = watch('thirdParty');
`showThirdParty` instead of `showTirdParty`

2024-10-18 16:24 UTC, loucass003 commented on gui/src/components/firmware-tool/BoardPinsStep.tsx
> +                    value: battery,
Yes it is, it is the value of the dropdown

2024-11-15 00:42 UTC, Eirenliel requested changes
TL;DR

2024-11-25 22:03 UTC, ImUrX requested changes

2024-11-27 16:07 UTC, ImUrX requested changes

2024-11-27 16:07 UTC, ImUrX commented on server/desktop/src/main/java/dev/slimevr/desktop/firmware/DesktopSerialFlashingHandler.kt
> +			println("Port closed")
use `LogManager.info`

2024-12-04 07:24 UTC, Eirenliel approved these changes

2024-12-16 16:08 UTC, loucass003 commented on gui/src/components/firmware-tool/FlashingMethodStep.tsx
> +    ),
nope it is not and there is no other way anyway

2024-12-19 15:35 UTC, ButterscotchV commented on server/core/src/main/java/dev/slimevr/firmware/FirmwareUpdateHandler.kt
> +	fun destroy() {
Is that not what `cancelUpdates()` is for? What is this method actually doing?

2024-12-19 15:35 UTC, ButterscotchV commented on server/core/src/main/java/dev/slimevr/firmware/FirmwareUpdateHandler.kt
> +		}
Can probably use a `when (status) {}` block here.

2024-12-19 15:35 UTC, ButterscotchV commented on server/core/src/main/java/dev/slimevr/firmware/OTAUpdateTask.kt
> +		private const val PORT = 8266
Is ESP32 not planned for support here? ESP32 uses port `3232` for OTA but pretty much everything else is the same iirc.

2024-12-19 17:35 UTC, merged