Add tray support
SlimeVR/SlimeVR-Server pull request #897
Opened 2023-11-11 20:37 UTC by ImUrX

Fixes #864

2023-11-13 00:13 UTC, Louka3000 requested changes

2023-11-13 00:13 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +settings-general-interface-use_tray-description = Let's you close the window without stopping the SlimeVR server so you can continue using it without having the GUI bothering you.
```suggestion
settings-general-interface-use_tray-description = Lets you close the window without closing the SlimeVR Server so you can continue using it without having the GUI bothering you.
```

2023-11-13 00:13 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +settings-general-interface-use_tray = Close to system tray
```suggestion
settings-general-interface-use_tray = Minimize to system tray
```

2023-11-13 00:13 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +settings-general-interface-use_tray-label = Close to system tray
```suggestion
settings-general-interface-use_tray-label = Minimize to system tray
```

2023-11-13 00:13 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +tray_or_exit_modal-description = This let's you choose if you want to exit or close to tray when pressing the close button.
```suggestion
tray_or_exit_modal-description = This lets you choose whether you want to close the server or to minimize it to the tray when pressing the close button.
```

2023-11-13 00:13 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +    You can later change this in the interface settings!
```suggestion
    You can change this later in the interface settings!
```

2023-11-18 18:35 UTC, Louka3000 approved these changes

2024-02-02 00:21 UTC, loucass003 approved these changes

2024-02-08 03:05 UTC, ButterscotchV approved these changes
Looks fine, can't review the Rust code thoroughly.

2024-02-10 00:44 UTC, merged