Complete TODO of replacing quatToXyzAngles with toEulerAngles
SlimeVR/SlimeVR-Server pull request #915
Opened 2023-12-28 23:56 UTC by VocalFan

Replaces `angleBuf = quatToXyzAngles(rot.unit(), angleBuf);` with `EulerAngles eulerIntrinsic = rot.unit().toEulerAngles(EulerOrder.XYZ);`

Since this also makes quatToXyzAngles now unused anywhere in the code, I decided to delete the unused function to save space.

2023-12-29 00:44 UTC, ButterscotchV approved these changes
Looks good, I wanna do a quick test with it to make sure functionality is the same, but this todo has been here for a bit, good job

2023-12-29 01:08 UTC, VocalFan commented
> Looks good, I wanna do a quick test with it to make sure functionality is the same, but this todo has been here for a bit, good job

Mhmm! Just doing what I can, not the best at Java *I took like, a single class on it.*

And I don't know much about the ~~functions~~ methods in this project.

2023-12-29 02:29 UTC, ImUrX approved these changes
very cool, hope to see you again in the future :3

2023-12-29 02:43 UTC, VocalFan commented
> very cool, hope to see you again in the future :3

Rust is more my thing but uh, I don't see much in the rust repo that is beginner lol

2023-12-29 03:16 UTC, ImUrX commented
we also have some rust in here if you want to refactor, its in `gui/src-tauri`

2024-01-06 23:32 UTC, Louka3000 requested changes
EulerOrder must be ZXY

2024-01-06 23:32 UTC, Louka3000 commented on server/core/src/main/java/dev/slimevr/posestreamer/BVHFileStream.java
>  		// Roll (X), pitch (Y), yaw (Z) (intrinsic)
```suggestion
		// pitch (X), yaw (Y), roll (Z)
```

2024-01-06 23:32 UTC, Louka3000 commented on server/core/src/main/java/dev/slimevr/posestreamer/BVHFileStream.java
> +		EulerAngles eulerIntrinsic = rot.unit().toEulerAngles(EulerOrder.XYZ);
```suggestion
		EulerAngles angles = rot.toEulerAngles(EulerOrder.ZXY);
```

2024-01-06 23:32 UTC, Louka3000 commented on server/core/src/main/java/dev/slimevr/posestreamer/BVHFileStream.java
>  		// Output in order of roll (Z), pitch (X), yaw (Y) (extrinsic)
```suggestion
		// Output in order of roll (Z), pitch (X), yaw (Y)
```

2024-01-07 04:34 UTC, ButterscotchV approved these changes

2024-01-07 04:36 UTC, Louka3000 approved these changes

2024-01-07 04:39 UTC, merged