Fix state bug on tray exit
SlimeVR/SlimeVR-Server pull request #944
Opened 2024-02-17 22:55 UTC by ImUrX

The first time you configure if you want to use the tray, the topbar might still think config is null for `useTray`. This just fixes it

2024-03-06 00:08 UTC, ButterscotchV approved these changes

2024-03-13 17:47 UTC, Louka3000 requested changes

2024-03-13 17:47 UTC, Louka3000 commented on gui/src/components/TopBar.tsx
> +          // forceUpdate()
```suggestion
```
leftover from debugging?

2024-03-13 18:00 UTC, Louka3000 approved these changes

2024-03-13 23:08 UTC, merged