Add missing head tracker status
SlimeVR/SlimeVR-Server pull request #962
Opened 2024-03-18 01:39 UTC by ImUrX

Based on top of #959

2024-03-30 17:10 UTC, ImUrX commented
Haven't tested it yet!

2024-03-31 04:40 UTC, ImUrX commented
i tested it and it seems to work, status system is a little finicky in the GUI side, sometimes packets are lost, it should be solved someday tbh

2024-06-06 01:42 UTC, Erimelowo requested changes

2024-06-06 01:42 UTC, Erimelowo commented on server/core/src/main/java/dev/slimevr/tracking/processor/HumanPoseManager.kt
> +				// This can't be solved with a yaw reset, it requires a full reset
This can be solved with a yaw reset

2024-06-06 01:42 UTC, Erimelowo commented on server/core/src/main/java/dev/slimevr/tracking/processor/HumanPoseManager.kt
> +		// TODO: Should this be ran anyways if headTracker is null or is not an HMD?
It needs to be ran if headTracker is null (specifically when the previous headTracker was computed). Doesn't need to be ran if headTracker is not computed as IMU head trackers will be adjusted to Identity.

2024-06-06 01:42 UTC, Erimelowo commented on server/core/src/main/java/dev/slimevr/tracking/processor/HumanPoseManager.kt
> +			skeleton.headTracker?.isHmd != true
Should probably check for isComputed instead
```suggestion
			skeleton.headTracker?.isComputed != true
```

2024-06-17 17:28 UTC, Erimelowo approved these changes

2024-06-19 06:20 UTC, ButterscotchV approved these changes

2024-07-11 15:50 UTC, merged