Add toggle to save and load mounting reset
SlimeVR/SlimeVR-Server pull request #963
Opened 2024-03-21 19:53 UTC by Louka3000

Useful for people with suits like my friend GizmoQC ;)

2024-03-21 19:59 UTC, Louka3000 commented
![slimevr_zC6d6RMCZk](https://github.com/SlimeVR/SlimeVR-Server/assets/20461725/d1fa7439-a561-407e-b092-ecc15beeec12)

2024-03-21 20:06 UTC, Louka3000 commented
Merge https://github.com/SlimeVR/SlimeVR-Server/pull/953 before this.

2024-04-01 23:34 UTC, ImUrX requested changes
if you want more gap between the title and the description use something like `gap-3`x.

there is merge conflicts, i will review the rest after fixing that

2024-04-01 23:34 UTC, ImUrX commented on gui/src/components/settings/pages/GeneralSettings.tsx
> +            <div className="flex gap-5 pt-5 pb-7 md:flex-row flex-col">
modify the actual div that you are making please
```suggestion
            <div className="flex gap-5 pt-5 md:flex-row flex-col">
```

2024-04-01 23:34 UTC, ImUrX commented on gui/src/components/settings/pages/GeneralSettings.tsx
> +            </div>
```suggestion
            <div className="flex flex-col pt-2 pb-3">
              <Typography bold>
                {l10n.getString(
                  'settings-general-tracker_mechanics-save_mounting_reset'
                )}
              </Typography>
              <Localized
                id="settings-general-tracker_mechanics-save_mounting_reset-description"
                elems={{ b: <b></b> }}
              >
                <Typography color="secondary"></Typography>
              </Localized>
            </div>
```

2024-04-03 19:39 UTC, ImUrX approved these changes

2024-04-04 00:22 UTC, Louka3000 commented
Needs https://github.com/SlimeVR/SolarXR-Protocol/pull/133

2024-04-04 02:35 UTC, Louka3000 commented
CI will fail because solarxr doesn't have yaw smoothing

2024-04-04 15:55 UTC, Louka3000 commented
Good for merge (solarxr points to main and CI is gud)

2024-04-04 23:37 UTC, ButterscotchV approved these changes

2024-04-04 23:53 UTC, merged