Connect one tracker at a time text adjustment
SlimeVR/SlimeVR-Server pull request #965
Opened 2024-03-23 23:07 UTC by ZRock35

Fixes a small line of text to be more clear that one tracker should be connected at a time when setting up

2024-03-23 23:10 UTC, Louka3000 reviewed
Don't we already have a tip for turning the tracker on? Pointing this out as DIY tracker users may not want to turn them on...

2024-03-23 23:10 UTC, Louka3000 commented
![slimevr_5GzgllYrXC](https://github.com/SlimeVR/SlimeVR-Server/assets/20461725/69b3b153-37a9-43fd-9e21-d1e6861030c6)

2024-03-23 23:11 UTC, Louka3000 requested changes

2024-03-23 23:11 UTC, Louka3000 commented on gui/public/i18n/en/translation.ftl
> +onboarding-connect_tracker-description-p1 = Connect one tracker at a time through a USB port and turn it on.
```suggestion
onboarding-connect_tracker-description-p1 = Connect each tracker one at a time through a USB port.
```

2024-03-24 00:06 UTC, ImUrX requested changes

2024-03-24 00:06 UTC, ImUrX commented on gui/public/i18n/en/translation.ftl
> +onboarding-connect_tracker-description-p1 = Connect each tracker one at a time through a USB port.
Change the translation key so other languages are forced to retranslate it
```suggestion
onboarding-connect_tracker-description-p0-v1 = Now onto the fun part, connecting trackers!
onboarding-connect_tracker-description-p1-v1 = Connect each tracker one at a time through a USB port.
```

2024-03-24 00:28 UTC, ImUrX approved these changes
lgtm

2024-03-24 00:46 UTC, Louka3000 approved these changes
Now learn Kotlin and typescript

2024-03-24 00:46 UTC, merged