macOS app naming improvements
SlimeVR/SlimeVR-Server pull request #991
Opened 2024-04-14 19:50 UTC by i0ntempest

Sets "SlimeVR Server" as app name in multiple locations. In the future this could be replaced by `displayName` if [tauri ever implement it](https://github.com/tauri-apps/tauri/issues/8109).

2024-04-14 20:04 UTC, ImUrX requested changes
The SlimeVR Server is not the GUI, and the app is specifically the GUI

Please change it to SlimeVR

2024-04-14 20:52 UTC, i0ntempest commented
> The SlimeVR Server is not the GUI, and the app is specifically the GUI

Okay, but the windows installer installs a “SlimeVR Server” shortcut into start menu that launches the GUI, so I wonder why is it not appropriate here? It’s the name for the package that contains both GUI and server.

2024-04-14 21:00 UTC, ImUrX commented
And we also have the linux desktop file which is just `SlimeVR`, we have the binary called `slimevr.exe` in Windows.

I don't really know the reason for why it's called `SlimeVR Server` in the start menu but I suspect it's been like that since the start and having to change it seems like too much problem.

2024-04-14 21:38 UTC, ImUrX commented
why are you signing the app

2024-04-14 21:40 UTC, i0ntempest commented
> why are you signing the app

Do you not want that? I was just about to say I added that because without a signature users are probably going to have problems launching the app because macOS Gatekeeper is only getting stricter.

2024-04-14 21:48 UTC, ImUrX commented
I mean, we don't have any signature to sign it with XD. Or does every macOS come with a user signature?

2024-04-14 21:54 UTC, i0ntempest commented
> I mean, we don't have any signature to sign it with XD. Or does every macOS come with a user signature?

I signed with `-` identity which is local adhoc signature. It's not a developer identity but should be better than flat out no signature.

Also idealy version of the app bundle should match github releases, right now I believe it's inherting the GUI version. Do you want that to be overwritten in Info.plist as well?

2024-04-14 21:58 UTC, ImUrX commented
then its fine to sign it.

the version stuff, it would be nice to fix the actual issue, the `package.json` of `gui` is not the same as the git tag and i don't really know how to fix it

2024-04-14 23:12 UTC, i0ntempest commented
> the version stuff, it would be nice to fix the actual issue, the `package.json` of `gui` is not the same as the git tag and i don't really know how to fix it

It's possible with `npm version`, but it's usually used to create/manage git tags, not the other way around (following existing git tags). I'm experimenting with it now, there should be a way around.

2024-04-15 03:17 UTC, i0ntempest commented
I kinda figured it out. Workflows triggered by releases will have their version in `gui/packages.json` corrected but that will also make the build dirty. To truely get around this I guess you really need to use `npm version` the way it meant to be used.

2024-04-15 17:04 UTC, ImUrX requested changes
let's leave this for another PR

2024-04-15 17:04 UTC, ImUrX commented on .github/workflows/gradle.yaml
> +          fi
```suggestion
```
i have another way to fix this, but it's gonna be in another PR.
Mind removing this? :3

2024-04-15 18:02 UTC, ImUrX approved these changes

2024-06-14 15:50 UTC, merged