Prepare Firmware Constants for Gestures Release
SlimeVR/SlimeVR-Server pull request #997
Opened 2024-04-21 06:11 UTC by 9il

The site is empty because we are in stealth mode.
https://www.gestures.space/

On the other hand, I can share photo of our prototype based on nRF5340 and ICM-42688 from 2024.

Complementary PRs:
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/413
https://github.com/SlimeVR/SolarXR-Protocol/pull/167

![IMG_2923](https://github.com/user-attachments/assets/92537369-8282-4be1-baff-ed705d54b2aa)

2024-06-18 17:41 UTC, ImUrX reviewed
we currently can't merge this kind of stuff before we are able to see a sample of the product or the code itself if its open-source.

2024-06-24 12:58 UTC, 9il commented
What open source contribution Sony made that is more valuable then ours?

We want to make a product with SlimeVR support from the start.

2025-01-02 22:39 UTC, Eirenliel commented
Please:

1) Link to your project
2) Make PRs for Firmware & SolarXR too

2025-03-30 12:49 UTC, 9il commented
@Eirenliel Done. Please see the PR description. Please merge this ASAP, it could be very helpful.

2025-03-30 14:49 UTC, Eirenliel requested changes

2025-03-30 14:49 UTC, Eirenliel commented on server/core/src/main/java/dev/slimevr/tracking/trackers/udp/FirmwareConstants.kt
> +	GESTURES(21u), // https://www.gestures.space/
```suggestion
	GESTURES(21u),
```
We do not ocmment on any of the types, especially with links https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/413#discussion_r2020167835

2025-03-30 15:03 UTC, 9il commented on server/core/src/main/java/dev/slimevr/tracking/trackers/udp/FirmwareConstants.kt
> +	GESTURES(21u), // https://www.gestures.space/
I thought this is what you asked about the link. Removed.

2025-03-30 15:19 UTC, Eirenliel approved these changes

2025-03-30 15:19 UTC, merged

2025-03-30 16:01 UTC, 9il commented
thanks